package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

// Note: Introspection resolvers (__InputValue, __Type) are handled automatically
// by gqlgen v0.17.45 and do not need to be implemented manually.
